### ISSUE TITLE
linux start-up crash

### ISSUE THREAD

**Issue by DungeonLord87** [Infiland/AsteroidsFeedback#18]
since patch 1.0.1 i've been checking every day after work if the game will start so i can try it and so far every time its crashed on start-up.

i run mx 21 (6.5 kernel) on my desktop and lmde 6 on my laptop (6.1 kernel), both 64 bit fully updated with intel/intel for the laptop and amd/amd for the desktop, and the game hasnt started on either. since the game doesnt even start before crashing the only info i can provide is what i get in terminal when trying to start the game

/chdir "/mnt/7eb88424-f125-4859-be57-d50d38c3f39e/SteamLibrary/steamapps/common/Asteroids ++"
ERROR: ld.so: object '/home/dungeonlord/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/dungeonlord/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/dungeonlord/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Adding process 19122 for gameID 2407300
Adding process 19123 for gameID 2407300
ERROR: ld.so: object '/home/dungeonlord/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/mnt/7eb88424-f125-4859-be57-d50d38c3f39e/SteamLibrary/steamapps/common/Asteroids ++/assets/ast.sh: line 3: /home/dungeonlord/.steam/steam/steamapps/common/Asteroids ++/Asteroids ++: No such file or directory
pid 19128 != 19124, skipping destruction (fork without exec?)
Adding process 19124 for gameID 2407300
Uploaded AppInterfaceStats to Steam
Game Recording - game stopped [gameid=2407300]
Removing process 19124 for gameID 2407300
Removing process 19123 for gameID 2407300
Removing process 19122 for gameID 2407300

**Comment by zone-a-1** [comment]
I'm not the dev of the game, but based on this error message `/home/dungeonlord/.steam/steam/steamapps/common/Asteroids ++/Asteroids ++: No such file or directory` and that the path in the line `/mnt/7eb88424-f125-4859-be57-d50d38c3f39e/SteamLibrary/steamapps/common/Asteroids ++/assets/ast.sh: line 3:` contains "SteamLibrary" I think that you have the game installed in a non-default directory. You can see that in these logs are two different paths that are being used. Now if that's the problem there are a few ways to fix that:
1. Install the game in the regular steamapps directory
2. Copy the contents of `/mnt/7eb88424-f125-4859-be57-d50d38c3f39e/SteamLibrary/steamapps/common/Asteroids ++/` to `/home/dungeonlord/.steam/steam/steamapps/common/Asteroids ++/`
3. Edit this script `/mnt/7eb88424-f125-4859-be57-d50d38c3f39e/SteamLibrary/steamapps/common/Asteroids ++/assets/ast.sh` to point to the `/mnt/7eb88424-f125-4859-be57-d50d38c3f39e/SteamLibrary/steamapps/common/Asteroids ++/` directory instead of something that probably looks like `/home/$USER/.steam/steam/steamapps/common/Asteroids ++/Asteroids ++`

**Comment by Infiland** [comment]
I haven't updated the game on linux to the most recent version of Asteroids ++, so I'm going to try to work on that! Did you try to use proton?

**Comment by DungeonLord87** [comment]
> I haven't updated the game on linux to the most recent version of Asteroids ++, so I'm going to try to work on that! Did you try to use proton?

i have not tried it with proton yet. 


> I'm not the dev of the game, but based on this error message `/home/dungeonlord/.steam/steam/steamapps/common/Asteroids ++/Asteroids ++: No such file or directory` and that the path in the line `/mnt/7eb88424-f125-4859-be57-d50d38c3f39e/SteamLibrary/steamapps/common/Asteroids ++/assets/ast.sh: line 3:` contains "SteamLibrary" I think that you have the game installed in a non-default directory. You can see that in these logs are two different paths that are being used. Now if that's the problem there are a few ways to fix that:
> 
>     1. Install the game in the regular steamapps directory
> 
>     2. Copy the contents of `/mnt/7eb88424-f125-4859-be57-d50d38c3f39e/SteamLibrary/steamapps/common/Asteroids ++/` to `/home/dungeonlord/.steam/steam/steamapps/common/Asteroids ++/`
> 
>     3. Edit this script `/mnt/7eb88424-f125-4859-be57-d50d38c3f39e/SteamLibrary/steamapps/common/Asteroids ++/assets/ast.sh` to point to the `/mnt/7eb88424-f125-4859-be57-d50d38c3f39e/SteamLibrary/steamapps/common/Asteroids ++/` directory instead of something that probably looks like `/home/$USER/.steam/steam/steamapps/common/Asteroids ++/Asteroids ++`

yeah i have it installed on a separate nvme just for my games...

**Comment by Infiland** [comment]
See how the game runs now in the latest update (1.1.1c) on linux. Btw ast.sh was supposed to run Asteroids___ and not Asteroids ++ so this should fix the problem where steam couldn't run the game.
