### ISSUE TITLE
Wasted Money

### ISSUE THREAD

**Issue by Krosidaan** [Infiland/AsteroidsFeedback#27]
I bought the 2,000 ticket item and it charged my account and took my money but never gave me anything.

**Comment by Infiland** [comment]
Hello, purchased items like 2000 credits can be activated by going in the game to Extras > Steam Inventory and then choosing the item.
Please let me know if you have received 2000 credits this way or if there are further problems, I will try my best to fix this if it goes wrong

Edit: seems this issue is resolved
