### ISSUE TITLE
Full Review

### ISSUE THREAD

**Issue by Mason111h** [Infiland/AsteroidsFeedback#33]
Hey dude! Loving the game so far but I want to give some feedback after about 6 hours of gameplay:

For starters the game is really fun to play and the asteroid mechanics are a lot of fun. This feels a lot like vampire survivors which I love. However, when you really start to get going the campaign ends and you're basically reset so you never hit that satisfying end game. You do have the skill tree which is a cool idea but hitting the end of the skill tree on one thing to unlock the big power up is very expensive. Some of how the utilities function is also unclear. The whole rhythm mechanic in the top right that goes up to S. Absolutely 0 clue the purpose of function of that.

I beat the first two campaign parts but now I'm stuck and unsure of what to do next or how to unlock the next levels. Instead of the difficulty nerfing the playing I think buffing the enemies would make the experience more fun. Bigger numbers and more abilities on screen gives a nice dopamine hit. 

Anyways. Cool game. Thanks for making it.

**Comment by Infiland** [comment]
Hey thank you for liking it!

The ending of the game is abrupt, I was thinking to add something meaningful, like an ending cutscene, but I have other plans as during development I wasn't really sure what the ending of the game is going to be, but I have a rough idea now (it's probably going to be something with the computer, if you've searched that part of the area) but I won't be exploring that part of the game yet, as the game is probably going to go for an 'endless approach', after all, Asteroids is supposed to be filled with endless gameplay!

As for campaigns, the first 2 campaigns (Main and Pluto) are free, others can be unlocked by gathering planets (so trading/buying planets), and it's a way for me to earn money from the game. I am not going for DLCs (yet) because the dropped items you get are free, so technically each campaign is 'free' but turns out grindy, which I'd say is controversial but the game's gotten positive feedback and nobody complained so ¯\_(ツ)_/¯

However I am planning to add new free content, like when I added weekly planets at launch, and in 1.2.0 I introduced daily levels, so I'll keep going and I'll add endless run, which was supposed to be at launch. It will act more like a 'roguelike' where you have to choose random weapons and choose skill tree upgrades to win... or well, get the highscore and compete with others! And also a level editor and steam workshop for free is planned, but I'll see how that goes depending on the playerbase.

The grade in the corner needs a rework and I agree it's confusing, right now it depends on how fast you beat waves, what the player health is and how fast do you beat asteroids, along with other factors like coin collecting.

I agree that nerfing weapons isn't fun, I only nerf broken weapons or I rework on existing weapons. I don't want the game to turn into 'Diablo 4' where the devs just nerf everything because there was just this one powerful weapon, however I don't want one weapon to be relied on everything. Each weapon should be unique and should work well/worse on specific asteroids. I am not really a fan of buffing asteroids either, as it affects every single weapon and artificially makes the game harder, but the only good that it does is 'improve performance' if I wanted to go for the approach to spawn less asteroids for more health, BUT MORE ASTEROIDS ARE COOLER!

Thanks for posting this, any feedback is valuable to me (reviews, videos etc!) so thank you again 😁😁 If you have suggestions let me know.
